### ISSUE TITLE
Units.energy is initialized as int16 but transformed to float32 in step()

### ISSUE THREAD

**Issue by LeFiz** [Lux-AI-Challenge/Lux-Design-S3#18]
After reset unit.energy is int16 but using step() turns it into a float32. This means the env can't be lax.scan'ed easily. 
It's easy to fix by just casting to int16 but the underlying reason it's a float seems to be that map_features.energy is float, although it is always round()'ed before usage. Would be better to change that if there is no reason for it being float32.

**Comment by StoneT2000** [comment]
energy can only be a integer, at intermediate steps it might be a float (to be multiplied then rounded)
