### ISSUE TITLE
Destroyed units are not removed at the end of turn

### ISSUE THREAD

**Issue by LeFiz** [Lux-AI-Challenge/Lux-Design-S3#27]
According to match resolution order a  unit that gets sapped to negative energy should be removed at step 5 of resolution. It should not be there at the start of the next turn, but in reality  it is (it is removed the very next turn though).

Edit: according to the comments in the code it's a feature so that the user can see the destroyed unit. But as was pointed out on discord: the dead units still generate points (as they are in unit_mask and therefore in compute_unit_counts_map) and the agent still generates actions for these units.

Sapped unit is still there with negative energy after turn resolves:

![image](https://github.com/user-attachments/assets/67897aa3-fd75-412a-b3ce-0cca72612817)

**Comment by StoneT2000** [comment]
closed by #39
