### ISSUE TITLE
API documentation is missing 

### ISSUE THREAD

**Issue by kartik1pandey** [Lux-AI-Challenge/Lux-Design-S3#43]
![Screenshot 2024-12-16 154651](https://github.com/user-attachments/assets/1d0056ee-2f33-474b-a687-4cc3f8f3ddc9)

**Comment by StoneT2000** [comment]
the link is spelled wrong, it should be Lux-Design-S3, not Lux-Desig-S3, where did you find the wrong link?

**Comment by akshatvishu** [comment]
> the link is spelled wrong, it should be Lux-Design-S3, not Lux-Desig-S3, where did you find the wrong link?

It's the hyperlink labeled "this document" under the heading [Lux AI Season 3 Specifications](https://www.kaggle.com/competitions/lux-ai-season-3/overview/lux-ai-season-3-specifications) on Kaggle points to the wrong address as shared above.

**Comment by StoneT2000** [comment]
thanks, fixed now.
