### ISSUE TITLE
tiles that are invisible before shift stay invisible after shift

### ISSUE THREAD

**Issue by nnaineni** [Lux-AI-Challenge/Lux-Design-S3#45]
seed: 2944624

check tile (23, 5). on step 61 this tile is still invisible even though it is in range and is empty space. is this intended?

![{14B682B0-3513-4779-BD28-95E77D96AE01}](https://github.com/user-attachments/assets/29c92992-efb6-4a1e-9973-ad10f8bfb8a7)

**Comment by CJBoey** [comment]
The behaviour is correct according to the match resolution order

> 1. Move all units that have enough energy to move
> 2. Execute the sap actions of all units that have enough energy to do so
> 3. Resolve collisions and apply energy void fields
> 4. Update the energy of all units based on their position (energy fields and nebula tiles)
> 5. Spawn units for all teams. Remove units that have less than 0 energy.
> 6. **Determine the team vision / sensor masks for all teams and mask out observations accordingly**
> 7. **Environment objects like asteroids/nebula tiles/energy nodes move around in space**
> 8. Compute new team points

**Comment by StoneT2000** [comment]
@CJBoey is correct here.

**Comment by vkrajnak** [comment]
Match resolution order is ok, but what about having a consistent vision reduction? In the example two nebula tiles are visible, which is ok if vision reduction is 0 and an empty tile is invisible for no obvious reason.
