### ISSUE TITLE
Asteroids blocking spawn location

### ISSUE THREAD

**Issue by LeFiz** [Lux-AI-Challenge/Lux-Design-S3#8]
Asteroids can surround the starting location or the spawn can even be on an asteroid, making the episode unplayable.

Possible solutions:
- keep a small area (like 3x3) around the spawn free of all map features
- make asteroids spawn more sparsely instead of in large blocks; makes map more connected while still being moving obstacles

Related: Relics are not necessarily reachable from spawns (see 2nd screenshot).

Example:

![image](https://github.com/user-attachments/assets/ef5df8b4-3f0e-456c-9db8-3aeb822c4519)

![image](https://github.com/user-attachments/assets/944fa6cb-ccc0-4733-bd99-2af9fb7a1c28)

**Comment by StoneT2000** [comment]
Relic node tiles not being reachable in my opinion is perfectly fine. The way to win the game now is to accrue the most energy in the game.

I am open to modifying the initial asteroid tile placements though. But i would like to avoid writing an algo to check pathability from team A to B which can slow down the env / reject maps.

**Comment by LeFiz** [comment]
Mostly fixed with #16
